// NOTE on file extension: this is `.tsx`, not `.ts`. The project's
// `next.config.ts` sets `pageExtensions: ["tsx","jsx","js"]` (so a bare
// `middleware.ts` isn't mistaken for a page) — which means Next's
// file-based metadata API ignores `robots.ts` / `sitemap.ts`. Using `.tsx`
// puts them back in the page-extension set without changing the rule.
// The file contains no JSX; the extension is purely a registration trick.

import type { MetadataRoute } from "next";

const SITE_URL =
  process.env.NEXTAUTH_URL ??
  (process.env.VERCEL_URL ? `https://${process.env.VERCEL_URL}` : "http://localhost:3000");

/**
 * /robots.txt — generated by Next's file-based metadata API.
 *
 * Allow the marketing surface (`/`, `/pricing`, `/signup`, `/cgu`, `/privacy`).
 * Disallow:
 *   - /api/*        — never any value for an indexer to scrape
 *   - /app/*        — authed shopper surface; behind a session check anyway
 *   - /pro/*        — authed brand surface
 *   - /dashboard/*  — legacy admin surface
 *   - /checkout, /checkout/*  — transactional, not a landing page
 *   - /widget       — brand-embedded iframe, not for crawlers
 *   - /login        — also `noindex` at the meta level (defence in depth)
 *
 * The sitemap pointer plus host directive help GSC / Bing pick up the
 * canonical hostname after first crawl.
 */
export default function robots(): MetadataRoute.Robots {
  return {
    rules: [
      {
        userAgent: "*",
        allow: "/",
        disallow: [
          "/api/",
          "/app/",
          "/pro/",
          "/dashboard/",
          "/checkout",
          "/checkout/",
          "/widget",
          "/login",
        ],
      },
    ],
    sitemap: `${SITE_URL}/sitemap.xml`,
    host: SITE_URL,
  };
}
