// See `robots.tsx` for the .tsx-not-.ts note. Same reason here.

import type { MetadataRoute } from "next";

const SITE_URL =
  process.env.NEXTAUTH_URL ??
  (process.env.VERCEL_URL ? `https://${process.env.VERCEL_URL}` : "http://localhost:3000");

/**
 * /sitemap.xml — generated by Next's file-based metadata API.
 *
 * Lists every PUBLIC indexable URL. Login is omitted intentionally
 * (noindex in its metadata). The pro / app / dashboard surfaces are all
 * auth-walled and listed in robots.ts as disallowed.
 *
 * Why we set `lastModified` via the build-time epoch rather than `new Date()`:
 * the runtime forbids `new Date()` / `Date.now()` inside workflow scripts,
 * but route handlers run in the normal Node runtime where `new Date()` is
 * fine. Using a build-time constant keeps every sitemap fetch
 * deterministic between regenerations, which makes GSC's "changed?" check
 * cheap. If we later want per-route `lastModified` accuracy, swap this for
 * a DB query of the last edit timestamp per surface.
 */
const buildTime = new Date();

export default function sitemap(): MetadataRoute.Sitemap {
  return [
    {
      url: `${SITE_URL}/`,
      lastModified: buildTime,
      changeFrequency: "weekly",
      priority: 1.0,
    },
    {
      url: `${SITE_URL}/pricing`,
      lastModified: buildTime,
      changeFrequency: "monthly",
      priority: 0.8,
    },
    {
      url: `${SITE_URL}/signup`,
      lastModified: buildTime,
      changeFrequency: "monthly",
      priority: 0.6,
    },
    {
      url: `${SITE_URL}/cgu`,
      lastModified: buildTime,
      changeFrequency: "yearly",
      priority: 0.3,
    },
    {
      url: `${SITE_URL}/privacy`,
      lastModified: buildTime,
      changeFrequency: "yearly",
      priority: 0.3,
    },
  ];
}
